FROM python:3.12-slim

WORKDIR /app

# Install PostgreSQL client library
RUN apt-get update && \
    apt-get install -y libpq5 && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run the application
CMD uvicorn main:app --host 0.0.0.0 --port $PORT